/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Controller.MainControl;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author Administrator
 */
public class addPat extends javax.swing.JFrame {

    /** Creates new form addPat */
    public addPat() {
        this.setResizable(false);
        initComponents();
    }


    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        ptage = new javax.swing.JTextField();
        mname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jButtonAccept = new javax.swing.JButton();
        prn = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        diagnosis = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        pgender = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        addrss = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButtonAccept1 = new javax.swing.JButton();
        pdate = new javax.swing.JTextField();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        ptage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptageActionPerformed(evt);
            }
        });
        jPanel1.add(ptage);
        ptage.setBounds(220, 230, 230, 30);

        mname.setText("MI");
        mname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnameActionPerformed(evt);
            }
        });
        jPanel1.add(mname);
        mname.setBounds(420, 40, 40, 30);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 570, 0);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 50, 40, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Gender");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(110, 270, 50, 17);

        fname.setText("Firstname");
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        jPanel1.add(fname);
        fname.setBounds(310, 40, 100, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Age");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(120, 230, 30, 17);

        lname.setText("Lastname");
        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });
        jPanel1.add(lname);
        lname.setBounds(220, 40, 80, 30);

        jButtonAccept.setText("Add");
        jButtonAccept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAcceptMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonAccept);
        jButtonAccept.setBounds(540, 170, 100, 30);
        jPanel1.add(prn);
        prn.setBounds(220, 310, 230, 30);

        diagnosis.setColumns(20);
        diagnosis.setRows(5);
        jScrollPane1.setViewportView(diagnosis);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(220, 90, 250, 90);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Address");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(110, 200, 50, 14);

        pgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pgenderActionPerformed(evt);
            }
        });
        jPanel1.add(pgender);
        pgender.setBounds(220, 270, 230, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Diagnosis");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(110, 100, 70, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Room Number");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(90, 320, 90, 17);

        addrss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrssActionPerformed(evt);
            }
        });
        jPanel1.add(addrss);
        addrss.setBounds(220, 190, 230, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Date Admitted");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(90, 360, 100, 17);

        jButtonAccept1.setText("Edit");
        jButtonAccept1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAccept1MouseClicked(evt);
            }
        });
        jPanel1.add(jButtonAccept1);
        jButtonAccept1.setBounds(540, 220, 100, 30);
        jPanel1.add(pdate);
        pdate.setBounds(220, 360, 230, 30);

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication100/img/adminbg1.png"))); // NOI18N
        jPanel1.add(BG);
        BG.setBounds(0, 0, 680, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ptageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ptageActionPerformed

    private void mnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnameActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    private void jButtonAcceptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAcceptMouseClicked
        // TODO add your handling code here:
        
        try{
            String fname1 = fname.getText();
            String lname1 = lname.getText();
            String mname1 = mname.getText();
            String diag = diagnosis.getText();
            String addrss1 = addrss.getText();
            String gender = pgender.getText();
            int rn = Integer.parseInt(prn.getText());
            String ddate = pdate.getText();
            System.out.println(ddate);
            
            MainControl mc = new MainControl();
            mc.addPats(addrss1, fname1, lname1, mname1, diag, addrss1, rn, gender, rn, ddate);
            this.setVisible(false);
            new AdminHome4().setVisible(true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage());
        }
        
    }//GEN-LAST:event_jButtonAcceptMouseClicked

    private void pgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pgenderActionPerformed

    private void addrssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrssActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addrssActionPerformed

    private void jButtonAccept1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAccept1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAccept1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addPat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addPat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addPat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addPat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addPat().setVisible(true);
                DateFormat a = new SimpleDateFormat("yyyy-MM-dd");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    public javax.swing.JTextField addrss;
    public javax.swing.JTextArea diagnosis;
    public javax.swing.JTextField fname;
    public javax.swing.JButton jButtonAccept;
    public javax.swing.JButton jButtonAccept1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField lname;
    public javax.swing.JTextField mname;
    private javax.swing.JTextField pdate;
    public javax.swing.JTextField pgender;
    public javax.swing.JTextField prn;
    public javax.swing.JTextField ptage;
    // End of variables declaration//GEN-END:variables

}
