/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import View.DoctorModule;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import Model.Docz;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Leo James
 */
public class assignDoc extends javax.swing.JFrame {
    private int doc_set_id;
    
    /**
     * Creates new form assignDoc
     */
    public assignDoc() {
        initComponents();
        show_docs();
    }
    public void setdoc_set_id(int doc_set_id) {
        this.doc_set_id = doc_set_id;
    }
    
    public void close3(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    public ArrayList<Docz> docList(){
        ArrayList<Docz> docList = new ArrayList<>();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/icaredb?zeroDateTimeBehavior=exception","root","");
            String query5="SELECT * FROM doctors";
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query5);
            
            Docz docs;
            while(rs.next()){
                docs=new Docz(rs.getInt("doctor_id"),rs.getInt("user_id"),rs.getString("doctor_lname"),rs.getString("doctor_fname"),rs.getString("doctor_mi"),rs.getString("specialization"));
                docList.add(docs);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "User Authenticity Error: " + e.getMessage());
        }
        return docList;
    }
    
    public void show_docs(){
        ArrayList<Docz> docss = docList();
        DefaultTableModel model = (DefaultTableModel)jTableAssign.getModel();
        Object[] row = new Object[10];
        model.setRowCount(0);
        for(int i=0; i<docss.size();i++){
            row[0]=docss.get(i).getDoctor_id();
            row[1]=docss.get(i).getDoctor_lname();
            row[2]=docss.get(i).getDoctor_fname();
            row[3]=docss.get(i).getDoctor_mi();
            row[4]=docss.get(i).getSpecialization();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAssign = new javax.swing.JTable();
        jButtonAssign = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jTableAssign.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "LastName", "FirstName", "MI", "Specialization"
            }
        ));
        jTableAssign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAssignMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAssign);
        if (jTableAssign.getColumnModel().getColumnCount() > 0) {
            jTableAssign.getColumnModel().getColumn(2).setPreferredWidth(30);
            jTableAssign.getColumnModel().getColumn(3).setPreferredWidth(150);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 60, 820, 400);

        jButtonAssign.setText("Assign Doctor");
        jButtonAssign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAssignMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonAssign);
        jButtonAssign.setBounds(320, 10, 120, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication10/img/adminbg1.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 860, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 862, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableAssignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAssignMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableAssignMouseClicked

    private void jButtonAssignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAssignMouseClicked
        // TODO add your handling code here:
        Connection conn = null;
        ResultSet rs = null;
        int ii = jTableAssign.getSelectedRow();
        TableModel model =  jTableAssign.getModel();
        String mid = model.getValueAt(ii, 0).toString();
        
        try{
            String sql = "UPDATE `patientrec` SET `assignedDoctor`=? WHERE patientID =" + doc_set_id ;
            Class.forName("com.mysql.jdbc.Driver");
            conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/icaredb?zeroDateTimeBehavior=exception","root","");
            PreparedStatement pst = (PreparedStatement) conn.prepareStatement(sql);
            pst.setString(1, mid);
            int i = pst.executeUpdate();
            System.out.println("Updated");
            JOptionPane.showMessageDialog(null, "Successfully Assigned");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "ErawrXD");
        }
        DoctorModule docMod = new DoctorModule();
        docMod.setVisible(true);
        docMod.pack();
        docMod.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        close3();
    }//GEN-LAST:event_jButtonAssignMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(assignDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(assignDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(assignDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(assignDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new assignDoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAssign;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableAssign;
    // End of variables declaration//GEN-END:variables
}
