/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import View.PatientData;
import View.NurseModule;
import hms2.Sng_Back;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author Leo James
 */
public class widrawMeds extends javax.swing.JFrame {
    private int midID;
    /**
     * Creates new form PatientData
     */
    public widrawMeds() {
        initComponents();
    }
    public void setId(int midID) {
        this.midID = midID;
    }
    
    public void close1(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mqty = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        mamount = new javax.swing.JTextField();
        mform = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mname = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButtonSub = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mdesc = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        mqty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mqtyActionPerformed(evt);
            }
        });
        jPanel1.add(mqty);
        mqty.setBounds(220, 300, 230, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Quantity");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(130, 300, 60, 17);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 570, 0);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Amount");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(120, 140, 60, 17);

        mamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mamountActionPerformed(evt);
            }
        });
        jPanel1.add(mamount);
        mamount.setBounds(220, 140, 90, 30);

        mform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mformActionPerformed(evt);
            }
        });
        jPanel1.add(mform);
        mform.setBounds(220, 90, 240, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Form");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(120, 100, 50, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Description");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(120, 220, 70, 17);

        jLabel3.setText("mg");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(320, 140, 50, 30);

        mname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnameActionPerformed(evt);
            }
        });
        jPanel1.add(mname);
        mname.setBounds(220, 40, 240, 30);

        jButton1.setText("back");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 20, 55, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 50, 40, 17);

        jButtonSub.setText("Update");
        jButtonSub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSubMouseClicked(evt);
            }
        });
        jButtonSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSub);
        jButtonSub.setBounds(510, 210, 100, 30);

        mdesc.setColumns(20);
        mdesc.setRows(5);
        jScrollPane1.setViewportView(mdesc);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(220, 190, 250, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication10/img/adminbg1.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 680, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mqtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mqtyActionPerformed

    private void mamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mamountActionPerformed

    private void mformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mformActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mformActionPerformed

    private void mnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnameActionPerformed

    private void jButtonSubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSubMouseClicked
        // TODO add your handling code here:
        Connection conn = null;
        ResultSet rs = null;
        try{
            String sql = "UPDATE `medicinelist` SET `medicine_name`=? , `dosageForm`=? , `amount`=? , `medicine_desc`=? , `remaining`=? WHERE medicine_id =" + midID ;
            Class.forName("com.mysql.jdbc.Driver");
            conn=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/icaredb?zeroDateTimeBehavior=exception","root","");
            PreparedStatement pst = (PreparedStatement) conn.prepareStatement(sql);
            pst.setString(1, mname.getText());
            pst.setString(2, mform.getText());
            pst.setString(3, mamount.getText());
            pst.setString(4, mdesc.getText());
            pst.setString(5, mqty.getText());
            int i = pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Successfully Updated");
            
            NurseModule nMod = new NurseModule();
            nMod.setVisible(true);
            nMod.pack();
            nMod.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            close1();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "ErawrXD");
        }
    }//GEN-LAST:event_jButtonSubMouseClicked

    private void jButtonSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSubActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Sng_Back.instance().goPreviousPage(this);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new widrawMeds().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    public javax.swing.JButton jButtonSub;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField mamount;
    public javax.swing.JTextArea mdesc;
    public javax.swing.JTextField mform;
    public javax.swing.JTextField mname;
    public javax.swing.JTextField mqty;
    // End of variables declaration//GEN-END:variables
}
